In [1]:
import numpy as np

In [3]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
arrAux = np.arange(21,31).reshape(2,5)
arrAux

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
arr + arrAux

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [6]:
arr*3

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30]])

In [7]:
np.sqrt(arrAux)

array([[4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558]])

In [8]:
arrAux.max()

30

In [9]:
arrAux.argmax()

9

In [10]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])