In [1]:
import numpy as np

In [2]:
lst = [1,2,3]
lst

[1, 2, 3]

In [3]:
npArray = np.array(lst)
npArray

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,20) #return 20 equaly spaced numbers from 0 to 10, it's different from the arange function.
#It returns a one bracket array which means is a one dimensional array.

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [13]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(6)

array([0.56358184, 0.57041631, 0.36028894, 0.06871285, 0.23898259,
       0.69723218])

In [15]:
np.random.rand(3,3)

array([[0.78318025, 0.86023557, 0.21284948],
       [0.81261563, 0.25216373, 0.58341857],
       [0.96978276, 0.13250882, 0.7969749 ]])

In [16]:
np.random.randn(3)

array([-1.24444826, -0.73322656,  0.70051818])

In [19]:
np.random.randint(1,500,5) # 1 it's included and 500 is excluded 

array([294,  18, 460, 438, 399])

In [21]:
array = np.arange(25)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
randomArray = np.random.randint(0,40,10)
randomArray

array([ 3, 29, 16, 29, 12,  8, 38, 14, 31, 39])

In [23]:
np.reshape(array,(5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
randomArray.max()

39

In [25]:
randomArray.min()

3

In [26]:
#return the index of the value on the array
randomArray.argmax()

9

In [27]:
#same as befoder
randomArray.argmin()

0

In [29]:
array.shape

(25,)

In [30]:
array = array.reshape(5,5)
array.shape

(5, 5)

In [31]:
array.dtype

dtype('int64')